import { Actor, HttpAgent } from "@dfinity/agent";
import type { Identity } from "@dfinity/agent";

/**
 * Client for the backend's public-receipt and incident-notice methods.
 *
 * WHY THIS ISN'T IN backend.ts: that file is generated by caffeine-bindgen
 * and carries a "do not edit" banner. Rather than require the generator to be
 * installed to add two endpoints, this follows the pattern already used by
 * lib/ckMinter.ts — a hand-written partial IDL against the same canister.
 * Candid record subtyping means we decode only the fields we read.
 *
 * EVERY FUNCTION HERE DEGRADES TO "ABSENT" RATHER THAN THROWING. These
 * methods do not exist on the deployed canister until the backend upgrade
 * lands, and a frontend that crashes on a missing method would make the
 * deploy order load-bearing. Absent reads as "no incident" / "no receipt",
 * which is the correct pre-upgrade behaviour.
 */

const BACKEND_CANISTER_ID = "c626g-iyaaa-aaaau-agpoa-cai";
const HOST = "https://icp-api.io";

export type ReceiptKind = "refine" | "redeem";
export type ReceiptStatus = "paid" | "pulled" | "refunded" | "stranded";

export interface PublicReceipt {
  kind: ReceiptKind;
  /** e18 ckUNI for a refine; e8s sGLDT for a redeem. */
  amountIn: bigint;
  /** e8s sGLDT for a refine; e18 ckUNI for a redeem. */
  amountOut: bigint;
  /** 1e8-precision sGLDT per UNI, as settled. */
  rate: bigint;
  status: ReceiptStatus;
  timestampNs: bigint;
  pullBlock: bigint | null;
  payBlock: bigint | null;
}

export interface IncidentNotice {
  message: string;
  sinceNs: bigint;
  url: string | null;
}

// biome-ignore lint/suspicious/noExplicitAny: IDL factory is untyped by design
const idl = ({ IDL }: any) => {
  const RefineStatus = IDL.Variant({
    paid: IDL.Null,
    pulled: IDL.Null,
    refunded: IDL.Null,
    stranded: IDL.Null,
  });
  const ReceiptKind = IDL.Variant({ redeem: IDL.Null, refine: IDL.Null });
  const PublicReceipt = IDL.Record({
    amountIn: IDL.Nat,
    amountOut: IDL.Nat,
    kind: ReceiptKind,
    payBlock: IDL.Opt(IDL.Nat),
    pullBlock: IDL.Opt(IDL.Nat),
    rate: IDL.Nat,
    status: RefineStatus,
    timestamp: IDL.Int,
  });
  const IncidentNotice = IDL.Record({
    message: IDL.Text,
    sinceNs: IDL.Int,
    url: IDL.Opt(IDL.Text),
  });
  const TextResult = IDL.Variant({ err: IDL.Text, ok: IDL.Text });
  const UnitResult = IDL.Variant({ err: IDL.Text, ok: IDL.Null });
  return IDL.Service({
    getPublicReceipt: IDL.Func([IDL.Text], [IDL.Opt(PublicReceipt)], ["query"]),
    getIncidentNotice: IDL.Func([], [IDL.Opt(IncidentNotice)], ["query"]),
    getReceiptShareToken: IDL.Func(
      [ReceiptKind, IDL.Nat],
      [IDL.Opt(IDL.Text)],
      ["query"],
    ),
    publishReceipt: IDL.Func([ReceiptKind, IDL.Nat], [TextResult], []),
    unpublishReceipt: IDL.Func([ReceiptKind, IDL.Nat], [UnitResult], []),
  });
};

// biome-ignore lint/suspicious/noExplicitAny: actor shape follows the IDL
const makeActor = async (identity?: Identity): Promise<any> => {
  const agent = await HttpAgent.create(
    identity ? { identity, host: HOST } : { host: HOST },
  );
  return Actor.createActor(idl, { agent, canisterId: BACKEND_CANISTER_ID });
};

/** IDL.Opt decodes to [] | [value]. */
const opt = <T>(v: T[] | undefined): T | null =>
  Array.isArray(v) && v.length > 0 ? v[0] : null;

// biome-ignore lint/suspicious/noExplicitAny: decoding a Candid variant
const variantKey = (v: any): string => Object.keys(v ?? {})[0] ?? "";

/** Resolve a share token. null = unknown, revoked, or endpoint not deployed —
 *  all indistinguishable to the caller, which is intentional. */
export async function fetchPublicReceipt(
  token: string,
): Promise<PublicReceipt | null> {
  try {
    const actor = await makeActor();
    const raw = opt<Record<string, unknown>>(
      await actor.getPublicReceipt(token),
    );
    if (!raw) return null;
    return {
      kind: variantKey(raw.kind) as ReceiptKind,
      amountIn: raw.amountIn as bigint,
      amountOut: raw.amountOut as bigint,
      rate: raw.rate as bigint,
      status: variantKey(raw.status) as ReceiptStatus,
      timestampNs: raw.timestamp as bigint,
      pullBlock: opt<bigint>(raw.pullBlock as bigint[]),
      payBlock: opt<bigint>(raw.payBlock as bigint[]),
    };
  } catch {
    return null;
  }
}

/** null = nothing being reported, or the endpoint isn't deployed yet. */
export async function fetchIncidentNotice(): Promise<IncidentNotice | null> {
  try {
    const actor = await makeActor();
    const raw = opt<Record<string, unknown>>(await actor.getIncidentNotice());
    if (!raw) return null;
    const message = String(raw.message ?? "").trim();
    if (!message) return null;
    return {
      message,
      sinceNs: raw.sinceNs as bigint,
      url: opt<string>(raw.url as string[]),
    };
  } catch {
    return null;
  }
}

const kindArg = (kind: ReceiptKind) =>
  kind === "refine" ? { refine: null } : { redeem: null };

/** Existing share token for one of the caller's receipts, without minting one. */
export async function fetchShareToken(
  identity: Identity,
  kind: ReceiptKind,
  id: bigint,
): Promise<string | null> {
  try {
    const actor = await makeActor(identity);
    return opt<string>(await actor.getReceiptShareToken(kindArg(kind), id));
  } catch {
    return null;
  }
}

export type ShareResult =
  | { ok: true; token: string }
  | { ok: false; error: string };

/** Mint (or re-return) the share token. Idempotent on the backend. */
export async function publishReceipt(
  identity: Identity,
  kind: ReceiptKind,
  id: bigint,
): Promise<ShareResult> {
  try {
    const actor = await makeActor(identity);
    const res = await actor.publishReceipt(kindArg(kind), id);
    if ("ok" in res) return { ok: true, token: res.ok as string };
    return { ok: false, error: String(res.err) };
  } catch (e) {
    return {
      ok: false,
      error:
        e instanceof Error && /has no method|IDL error|Canister has no/.test(e.message)
          ? "Sharing isn't available yet — this feature ships with the next backend update."
          : "Couldn't create the link just now. Try again shortly.",
    };
  }
}

export async function unpublishReceipt(
  identity: Identity,
  kind: ReceiptKind,
  id: bigint,
): Promise<{ ok: boolean; error?: string }> {
  try {
    const actor = await makeActor(identity);
    const res = await actor.unpublishReceipt(kindArg(kind), id);
    if ("ok" in res) return { ok: true };
    return { ok: false, error: String(res.err) };
  } catch {
    return { ok: false, error: "Couldn't revoke the link just now." };
  }
}

/** The shareable URL for a token. */
export const shareUrl = (token: string): string =>
  `${window.location.origin}/r/${token}`;
