/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface sGLDTRequest {
    id: bigint;
    status: ExchangeStatus;
    submitter: Principal;
    bbTokenAmount: bigint;
    sgldAmountCalculated: bigint;
    timestamp: Time;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface UniDepositRequest {
    id: bigint;
    status: UNIDepositStatus;
    uniAmount: bigint;
    ethAddress: string;
    submitter: Principal;
    lockedExchangeRate?: bigint;
    sgldtPaid: bigint;
    timestamp: Time;
    txHash: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface TxRecord {
    id: string;
    status: TxStatus;
    description: string;
    tokenSymbol: string;
    timestamp: bigint;
    txType: TxType;
    amount: bigint;
    errorMsg?: string;
    ethTxHash?: string;
    icpBlockIndex?: bigint;
}
export interface BridgeRequest {
    id: bigint;
    status: BridgeStatus;
    ethAddress: string;
    submitter: Principal;
    batAmount: bigint;
    timestamp: Time;
}
export interface UserProfile {
    name: string;
}
export enum BridgeStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum TxStatus {
    Failed = "Failed",
    Confirmed = "Confirmed",
    Completed = "Completed",
    Pending = "Pending"
}
export enum TxType {
    Mint = "Mint",
    Refine = "Refine",
    Bridge = "Bridge",
    Transfer = "Transfer"
}
export enum UNIDepositStatus {
    pending = "pending",
    paid = "paid",
    confirmed = "confirmed",
    processing = "processing",
    failed = "failed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    /**
     * / Admin-only: add a transaction record on behalf of any user (e.g. for manual entries).
     */
    addTransaction(user: Principal, record: TxRecord): Promise<void>;
    /**
     * / Admin-only: Burns ckUNI from the treasury and releases UNI back to an Ethereum address.
     * / Calls the ICP ERC-20 minter withdrawal method to burn ckUNI and trigger UNI release on Ethereum.
     * / ckUNIAmount — amount in e8s (1e8 = 1 ckUNI).
     * / destinationEthAddress — the Ethereum address to receive the released UNI.
     */
    adminDissolveCkUNI(ckUNIAmount: bigint, destinationEthAddress: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    /**
     * / Admin-only: view any user's transaction history.
     */
    adminGetUserTransactions(user: Principal): Promise<Array<TxRecord>>;
    /**
     * / Admin-only alias for initializeMinterDepositAddress() that returns a result-style Text
     * / so the admin panel can display success/error feedback without trapping.
     */
    adminInitializeMinterAddress(): Promise<string>;
    /**
     * / Admin-only: Records a UNI→ckUNI mint event and calls the ICP ERC-20 minter
     * / to mint ckUNI directly to the treasury principal (72fnc-ziaaa-aaaai-axk4q-cai).
     * / ethTxHash — the Ethereum transaction hash proving UNI was sent to the deposit address.
     * / uniAmount — amount in e18 (ERC-20 standard, 1 UNI = 1_000_000_000_000_000_000).
     * /             ckUNI is an ERC-20 mirror token and always uses 18 decimal places — NOT e8s.
     */
    adminMintCkUNI(ethTxHash: string, uniAmount: bigint): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    /**
     * / Admin transfers ckUNI from this canister to any principal via ICRC-1.
     */
    adminTransferCkUNI(to: Principal, amount: bigint): Promise<string>;
    /**
     * / Admin transfers sGLDT from this canister's treasury to any principal via ICRC-1.
     */
    adminTransferSGLDT(to: Principal, amount: bigint): Promise<string>;
    approveBridgeRequest(id: bigint): Promise<void>;
    approveSGLDTExchangeRequest(id: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    calculateExchangeRate(batAmount: bigint): Promise<{
        bbTokenAmount: bigint;
        sgldAmount: bigint;
    }>;
    deprecated_getBridgeRequests(): Promise<Array<BridgeRequest>>;
    deprecated_getSGLDTRequests(): Promise<Array<sGLDTRequest>>;
    /**
     * / Diagnoses payout ability for a specific deposit — returns a human-readable summary.
     * / Shows the treasury sGLDT balance, exact amount required for this deposit,
     * / the fee, and whether the transfer would succeed with the current balance.
     * / Admin-only.
     */
    diagnosePayoutAbility(depositId: bigint): Promise<string>;
    getAllUNIDeposits(): Promise<Array<UniDepositRequest>>;
    getBalance(_principal: Principal): Promise<bigint>;
    getBatPrice(): Promise<bigint>;
    getBridgeRequests(): Promise<Array<BridgeRequest>>;
    getBridgeRequestsByUser(user: Principal): Promise<Array<BridgeRequest>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCanisterPrincipal(): Promise<Principal>;
    /**
     * / Returns the sGLDT balance held by the treasury (this canister's own account on the sGLDT ledger).
     * / Principal.fromActor(Self) == 72fnc-ziaaa-aaaai-axk4q-cai — this IS the treasury.
     * / Admin must send sGLDT to this canister's principal on the sGLDT ledger to fund payouts.
     * / Display: divide by 1e8 for human-readable sGLDT amount.
     */
    getCanisterSGLDTBalance(): Promise<bigint>;
    /**
     * / Returns the Ethereum deposit address that the user should send UNI to in order
     * / to receive ckUNI on ICP. If the address is not yet cached, this call auto-initializes
     * / it by calling the ICP ERC-20 minter (nbsys-saaaa-aaaar-qaaga-cai) once.
     * / The treasury principal (72fnc-ziaaa-aaaai-axk4q-cai) is always the owner/beneficiary.
     * / After initialization the address is cached permanently — subsequent calls are instant.
     * / Prefer getMinterDepositAddress() (query) once initialization has happened.
     */
    getCkUNIMinterDepositAddress(_userPrincipal: Principal): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    /**
     * / Returns the cached on-chain ckUNI balance held by the treasury principal (72fnc-ziaaa-aaaai-axk4q-cai).
     * / This is a query so it works for unauthenticated (anonymous) callers.
     * / Call refreshTreasuryBalances() to update the cache from the ckUNI ledger.
     */
    getCkUNITreasuryBalance(): Promise<bigint>;
    /**
     * / Public query: returns the current status of a UNI deposit for frontend polling.
     * / Any authenticated user may query their own deposit. Admin may query any deposit.
     * / Returns status as a Text string, the txHash, and the sGLDT amount paid (0 if not yet paid).
     */
    getDepositStatus(requestId: bigint): Promise<{
        status: string;
        sgldtPaid: bigint;
        txHash: string;
    }>;
    /**
     * / Public query — returns the cached treasury Ethereum deposit address for the ERC-20 minter.
     * / Falls back to the fixed hardcoded address (0x22582083361bf06579BbfFcC1138D3fc986B91FF)
     * / if the minter-derived address has not been initialized yet — so callers always get a
     * / non-empty, usable address.
     */
    getMinterDepositAddress(): Promise<string>;
    /**
     * / Returns the most recent non-paid UNI deposit for the caller (used by "Keep Checking" to
     * / recover the active deposit ID after a page refresh). Returns null if no active deposit exists.
     * / Also returns already-paid deposits so the UI can show a success screen instead of "not found".
     */
    getMyActiveDeposit(): Promise<{
        id: bigint;
        status: string;
        sgldtPaid: bigint;
        txHash: string;
    } | null>;
    /**
     * / Caller's own transaction history.
     */
    getMyTransactions(): Promise<Array<TxRecord>>;
    /**
     * / Alias kept for backward compatibility. Prefer getPayoutReadiness().
     */
    getPayoutDiagnostic(): Promise<{
        estimatedSGLDTNeeded: bigint;
        pendingDeposits: bigint;
        canisterSGLDTBalance: bigint;
    }>;
    /**
     * / Returns payout readiness info so the admin knows how much sGLDT is available
     * / and whether the treasury can cover all pending deposits.
     * / - treasurySGLDTBalance: sGLDT held by the treasury (this canister, e8s).
     * / - pendingDeposits: count of deposits in #confirmed or #failed status awaiting payout.
     * / - estimatedSGLDTNeeded: total sGLDT owed across all pending deposits (e8s).
     * / - treasuryPrincipal: the principal to send sGLDT to for top-up.
     */
    getPayoutReadiness(): Promise<{
        estimatedSGLDTNeeded: bigint;
        pendingDeposits: bigint;
        treasurySGLDTBalance: bigint;
        treasuryPrincipal: string;
    }>;
    getPendingBridgeRequests(): Promise<Array<BridgeRequest>>;
    getPendingSGLDTExchangeRequests(): Promise<Array<sGLDTRequest>>;
    /**
     * / Returns this canister's principal as Text — this IS the treasury (72fnc-ziaaa-aaaai-axk4q-cai).
     * / Admin must send sGLDT to this address on the sGLDT ledger (i2s4q-syaaa-aaaan-qz4sq-cai)
     * / to fund user payouts. No separate "refinery payout balance" exists — there is one treasury.
     */
    getRefineryPrincipal(): Promise<string>;
    getSGLDTExchangeRequests(): Promise<Array<sGLDTRequest>>;
    getSGLDTExchangeRequestsByUser(user: Principal): Promise<Array<sGLDTRequest>>;
    getSGLDTPrice(): Promise<bigint>;
    /**
     * / Returns the cached on-chain sGLDT balance held by the treasury principal (72fnc-ziaaa-aaaai-axk4q-cai).
     * / Used by the treasury banner at the top of the page.
     * / This is a query so it works for unauthenticated (anonymous) callers.
     * / Call refreshTreasuryBalances() to update the cache from the ledger.
     */
    getSGLDTTreasuryBalance(): Promise<bigint>;
    getTotalSupply(): Promise<bigint>;
    /**
     * / Returns cached ICRC-1 balances held by the treasury principal (72fnc-ziaaa-aaaai-axk4q-cai).
     * / This is a query so it works for unauthenticated callers.
     * / Call refreshTreasuryBalances() to pull fresh values from the ledgers.
     */
    getTreasuryICRC1Balances(): Promise<{
        ckUNIBalance: bigint;
        sgldtBalance: bigint;
    }>;
    getTreasuryStats(): Promise<{
        sGLDTTreasuryBalance: bigint;
        batPoolBalance: bigint;
    }>;
    /**
     * / Public query — returns treasury wallet info: cached deposit address, ckUNI balance (e8s), sGLDT balance (e8s).
     * / No authentication required — safe for all callers.
     * / Frontend divides raw Nat balances by 1e8 for display.
     * / depositAddress always returns a non-empty value: the minter-derived address when available,
     * / otherwise the fixed hardcoded fallback (0x22582083361bf06579BbfFcC1138D3fc986B91FF).
     */
    getTreasuryWalletInfo(): Promise<{
        sGLDTBalance: bigint;
        depositAddress: string;
        ckUNIBalance: bigint;
    }>;
    getUNIExchangeRate(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    /**
     * / Public query: returns the sGLDT ICRC-1 balance for any given principal (their own ICP account).
     * / No admin restriction — users can check their own balance.
     */
    getUserSGLDTBalance(principalText: string): Promise<bigint>;
    /**
     * / Returns all transactions for a given principal, newest-first. No auth restriction —
     * / the frontend passes the logged-in user's principal.
     */
    getUserTransactions(user: Principal): Promise<Array<TxRecord>>;
    getUserUNIDeposits(user: Principal): Promise<Array<UniDepositRequest>>;
    /**
     * / Admin-only: Calls the ICP ERC-20 minter to derive the treasury's fixed Ethereum
     * / deposit address and caches it on-chain. Only needs to be called once (or to refresh).
     * / All users will send UNI to this same address; the minter automatically converts
     * / incoming ERC-20 UNI to ckUNI and credits the treasury principal (72fnc-ziaaa-aaaai-axk4q-cai).
     */
    initializeMinterDepositAddress(): Promise<string>;
    /**
     * / Public query so the frontend can check whether the caller is the admin
     * / without any round-trip to the admin panel itself.
     */
    isAdminCaller(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    migrated_getAllBridgeRequests(): Promise<Array<BridgeRequest>>;
    migrated_getAllSGLDTRequests(): Promise<Array<sGLDTRequest>>;
    migration_updateBalance(_balance: bigint): Promise<void>;
    mintBankingBraveTokens(_to: Principal, _amount: bigint): Promise<void>;
    /**
     * / Fetches the live ICRC-1 balances for the treasury (this canister's own account) from both ledgers
     * / and stores them in the cache.
     * / This is an update call — anyone may call it to warm the cache.
     * / Called automatically after any admin transfer or sGLDT payout so the banner stays current.
     * / Note: Principal.fromActor(Self) == 72fnc-ziaaa-aaaai-axk4q-cai (they are the same).
     */
    refreshTreasuryBalances(): Promise<void>;
    rejectBridgeRequest(id: bigint): Promise<void>;
    rejectSGLDTExchangeRequest(id: bigint): Promise<void>;
    /**
     * / Allows a user to reset their own stuck mining phase (e.g. after a 20-minute timeout).
     * / This method only affects the UNI deposit state — it does NOT refund any tokens.
     * / Any #processing deposit belonging to the caller is reverted to #confirmed so the
     * / user can retry verifyAndPayUNIDeposit without reloading the page.
     * / Admin may reset any user's stuck deposit by passing the requestId.
     */
    resetMiningPhase(requestId: bigint): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    /**
     * / Retries the sGLDT payout for a deposit that is in #confirmed or #failed status.
     * /
     * / This is what the "Keep Checking" button should call. Unlike verifyEthTransaction,
     * / which only reads the current status, this method actually re-attempts the ICRC-1
     * / sGLDT transfer. Use this to resolve deposits that are stuck in #confirmed because
     * / a previous verifyAndPayUNIDeposit call trapped or failed silently.
     * /
     * / IMPORTANT: This function NEVER traps. All outcomes are returned as descriptive Text.
     * /   - If already paid:   "already_paid: <amount> sGLDT released to <principal>"
     * /   - If confirmed/failed and retry succeeds: "paid: <amount> sGLDT released to <principal>"
     * /   - If confirmed/failed and payout fails definitively: "confirmed_payout_failed: <reason>"
     * /   - If confirmed/failed and network/transient error: "failed: <reason>"
     * /   - If pending ETH:   "pending: ..."
     * /   - If processing:    "pending: ..."
     * /
     * / Only the original depositor or admin may call this.
     */
    retryUNIDepositPayout(requestId: bigint): Promise<string>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    /**
     * / Public (non-admin) method to trigger minter address initialization.
     * / Called by the frontend automatically when getMinterDepositAddress() returns "".
     * / Returns the cached address immediately if already set (fast path — no inter-canister call).
     * / If the cache is empty, calls the ICP ERC-20 minter (nbsys-saaaa-aaaar-qaaga-cai) to fetch
     * / the fixed treasury deposit address and caches it permanently on-chain.
     * / Any caller (authenticated or anonymous) may call this — it only mutates the address cache.
     */
    selfInitializeMinterAddress(): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    setBatPoolBalance(_balance: bigint): Promise<void>;
    /**
     * / Syncs the live exchange rate from the frontend CoinGecko feed to the backend.
     * / Called by the frontend after fetching UNI/sGLDT prices so the backend always uses
     * / the same rate the user sees. Only admin may call this; rate is in 1e8 precision
     * / (e.g. 238_000_000 = 2.38 sGLDT per UNI).
     */
    setLiveExchangeRate(newRate: bigint): Promise<void>;
    setSGLDTTreasuryBalance(_balance: bigint): Promise<void>;
    setUNIExchangeRate(rate: bigint): Promise<void>;
    submitBridgeRequest(ethAddress: string, batAmount: bigint): Promise<bigint>;
    submitSGLDTExchangeRequest(bbTokenAmount: bigint): Promise<bigint>;
    /**
     * / Records a UNI deposit after the frontend has confirmed the ETH transaction on-chain.
     * /
     * / Trust model: The frontend is responsible for confirming the ETH transaction via
     * / eth_getTransactionReceipt (using the connected Brave wallet) before calling this function.
     * / The backend trusts the frontend-submitted txHash, ethAddress, and uniAmount because:
     * /   1. The admin reviews and calls verifyAndPayUNIDeposit to release sGLDT.
     * /   2. A malicious user submitting a fake txHash would only create a pending record;
     * /      no sGLDT is released until the admin (or automated flow) explicitly approves it.
     * /   3. No Etherscan API key is required — ETH-side verification is client-side.
     * /
     * / Security:
     * /   - txHash must be in the valid Ethereum format: "0x" followed by exactly 64 hex characters.
     * /   - Duplicate txHash submissions are rejected to prevent double-deposit attacks.
     * /
     * / rateHint: Optional live exchange rate from the frontend (1e8 precision, e.g. 238_000_000 = 2.38 sGLDT/UNI).
     * /           When provided and > 0, this rate is locked for this deposit so the user receives
     * /           exactly what they saw on screen. Falls back to uniExchangeRate if null or 0.
     * /           This eliminates the need for a separate syncLiveExchangeRate call from the frontend.
     */
    submitUNIDeposit(ethAddress: string, uniAmount: bigint, txHash: string, rateHint: bigint | null): Promise<bigint>;
    /**
     * / Syncs the live market exchange rate from the frontend (CoinGecko) to the backend.
     * / ADMIN-ONLY: Only the admin principal may update the global exchange rate.
     * / Regular users should pass the live rate via submitUNIDeposit's rateHint parameter
     * / so the rate is locked per-deposit without mutating the global state.
     * / Rate is in 1e8 precision (e.g. 238_000_000 = 2.38 sGLDT per UNI).
     */
    syncLiveExchangeRate(newRate: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    /**
     * / Direct payout trigger — bypasses Etherscan re-check and immediately attempts
     * / the sGLDT ICRC-1 transfer for a deposit that is in #confirmed or #failed status.
     * /
     * / Use this when: the ETH transaction is confirmed but sGLDT was not released, and
     * / you want to force a payout retry without waiting for the next Etherscan poll cycle.
     * /
     * / Only the original depositor or admin may call this.
     * / NEVER traps — all outcomes returned as descriptive Text.
     */
    triggerSGLDTPayout(requestId: bigint): Promise<string>;
    /**
     * / Releases sGLDT from the treasury to the depositing user via ICRC-1 transfer.
     * /
     * / Trust model: The frontend confirms the ETH transaction before calling submitUNIDeposit,
     * / so by the time this function is called the deposit is already #confirmed. No Etherscan
     * / HTTP outcall is needed — ETH verification happens client-side.
     * /
     * / Race condition protection: Before the async ICRC-1 transfer, the deposit status is
     * / atomically set to #processing. Any concurrent call will see #processing and be rejected,
     * / preventing double-payout. On failure, the status reverts to #confirmed for retry.
     * /
     * / IMPORTANT: This function NEVER traps. All errors are returned as descriptive Text.
     * / On any failure the deposit reverts to #confirmed so the user can retry via Keep Checking.
     */
    verifyAndPayUNIDeposit(requestId: bigint): Promise<string>;
    /**
     * / Verifies an ETH transaction on Etherscan and auto-releases sGLDT if confirmed.
     * /
     * / Steps:
     * /   1. Looks up the deposit by requestId.
     * /   2. Makes an HTTP GET to the Etherscan API (gettxreceiptstatus endpoint).
     * /   3. If status=1 (success), marks the deposit #confirmed and calls verifyAndPayUNIDeposit.
     * /   4. Returns "confirmed_and_paid", "pending", "failed", or an error message.
     * /
     * / Any authenticated caller may verify their own deposit. Admin may verify any deposit.
     * / Returns "pending" on Etherscan timeout or API error so the frontend can retry safely.
     */
    verifyEthTransaction(requestId: bigint): Promise<string>;
}
import type { BridgeRequest as _BridgeRequest, BridgeStatus as _BridgeStatus, ExchangeStatus as _ExchangeStatus, Time as _Time, TxRecord as _TxRecord, TxStatus as _TxStatus, TxType as _TxType, UNIDepositStatus as _UNIDepositStatus, UniDepositRequest as _UniDepositRequest, UserProfile as _UserProfile, UserRole as _UserRole, sGLDTRequest as _sGLDTRequest } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addTransaction(arg0: Principal, arg1: TxRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTransaction(arg0, to_candid_TxRecord_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTransaction(arg0, to_candid_TxRecord_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async adminDissolveCkUNI(arg0: bigint, arg1: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDissolveCkUNI(arg0, arg1);
                return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDissolveCkUNI(arg0, arg1);
            return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetUserTransactions(arg0: Principal): Promise<Array<TxRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetUserTransactions(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetUserTransactions(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminInitializeMinterAddress(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.adminInitializeMinterAddress();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminInitializeMinterAddress();
            return result;
        }
    }
    async adminMintCkUNI(arg0: string, arg1: bigint): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminMintCkUNI(arg0, arg1);
                return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminMintCkUNI(arg0, arg1);
            return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminTransferCkUNI(arg0: Principal, arg1: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.adminTransferCkUNI(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminTransferCkUNI(arg0, arg1);
            return result;
        }
    }
    async adminTransferSGLDT(arg0: Principal, arg1: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.adminTransferSGLDT(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminTransferSGLDT(arg0, arg1);
            return result;
        }
    }
    async approveBridgeRequest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveBridgeRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveBridgeRequest(arg0);
            return result;
        }
    }
    async approveSGLDTExchangeRequest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveSGLDTExchangeRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveSGLDTExchangeRequest(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async calculateExchangeRate(arg0: bigint): Promise<{
        bbTokenAmount: bigint;
        sgldAmount: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateExchangeRate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateExchangeRate(arg0);
            return result;
        }
    }
    async deprecated_getBridgeRequests(): Promise<Array<BridgeRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.deprecated_getBridgeRequests();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deprecated_getBridgeRequests();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async deprecated_getSGLDTRequests(): Promise<Array<sGLDTRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.deprecated_getSGLDTRequests();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deprecated_getSGLDTRequests();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async diagnosePayoutAbility(arg0: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.diagnosePayoutAbility(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.diagnosePayoutAbility(arg0);
            return result;
        }
    }
    async getAllUNIDeposits(): Promise<Array<UniDepositRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUNIDeposits();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUNIDeposits();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBalance(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getBalance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBalance(arg0);
            return result;
        }
    }
    async getBatPrice(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getBatPrice();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBatPrice();
            return result;
        }
    }
    async getBridgeRequests(): Promise<Array<BridgeRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBridgeRequests();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBridgeRequests();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBridgeRequestsByUser(arg0: Principal): Promise<Array<BridgeRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBridgeRequestsByUser(arg0);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBridgeRequestsByUser(arg0);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCanisterPrincipal(): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.getCanisterPrincipal();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCanisterPrincipal();
            return result;
        }
    }
    async getCanisterSGLDTBalance(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCanisterSGLDTBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCanisterSGLDTBalance();
            return result;
        }
    }
    async getCkUNIMinterDepositAddress(arg0: Principal): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getCkUNIMinterDepositAddress(arg0);
                return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCkUNIMinterDepositAddress(arg0);
            return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCkUNITreasuryBalance(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCkUNITreasuryBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCkUNITreasuryBalance();
            return result;
        }
    }
    async getDepositStatus(arg0: bigint): Promise<{
        status: string;
        sgldtPaid: bigint;
        txHash: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDepositStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDepositStatus(arg0);
            return result;
        }
    }
    async getMinterDepositAddress(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getMinterDepositAddress();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMinterDepositAddress();
            return result;
        }
    }
    async getMyActiveDeposit(): Promise<{
        id: bigint;
        status: string;
        sgldtPaid: bigint;
        txHash: string;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyActiveDeposit();
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyActiveDeposit();
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyTransactions(): Promise<Array<TxRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTransactions();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTransactions();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPayoutDiagnostic(): Promise<{
        estimatedSGLDTNeeded: bigint;
        pendingDeposits: bigint;
        canisterSGLDTBalance: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayoutDiagnostic();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayoutDiagnostic();
            return result;
        }
    }
    async getPayoutReadiness(): Promise<{
        estimatedSGLDTNeeded: bigint;
        pendingDeposits: bigint;
        treasurySGLDTBalance: bigint;
        treasuryPrincipal: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayoutReadiness();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayoutReadiness();
            return result;
        }
    }
    async getPendingBridgeRequests(): Promise<Array<BridgeRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingBridgeRequests();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingBridgeRequests();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingSGLDTExchangeRequests(): Promise<Array<sGLDTRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingSGLDTExchangeRequests();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingSGLDTExchangeRequests();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRefineryPrincipal(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getRefineryPrincipal();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRefineryPrincipal();
            return result;
        }
    }
    async getSGLDTExchangeRequests(): Promise<Array<sGLDTRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSGLDTExchangeRequests();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSGLDTExchangeRequests();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSGLDTExchangeRequestsByUser(arg0: Principal): Promise<Array<sGLDTRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSGLDTExchangeRequestsByUser(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSGLDTExchangeRequestsByUser(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSGLDTPrice(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getSGLDTPrice();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSGLDTPrice();
            return result;
        }
    }
    async getSGLDTTreasuryBalance(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getSGLDTTreasuryBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSGLDTTreasuryBalance();
            return result;
        }
    }
    async getTotalSupply(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalSupply();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalSupply();
            return result;
        }
    }
    async getTreasuryICRC1Balances(): Promise<{
        ckUNIBalance: bigint;
        sgldtBalance: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getTreasuryICRC1Balances();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTreasuryICRC1Balances();
            return result;
        }
    }
    async getTreasuryStats(): Promise<{
        sGLDTTreasuryBalance: bigint;
        batPoolBalance: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getTreasuryStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTreasuryStats();
            return result;
        }
    }
    async getTreasuryWalletInfo(): Promise<{
        sGLDTBalance: bigint;
        depositAddress: string;
        ckUNIBalance: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getTreasuryWalletInfo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTreasuryWalletInfo();
            return result;
        }
    }
    async getUNIExchangeRate(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUNIExchangeRate();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUNIExchangeRate();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserSGLDTBalance(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserSGLDTBalance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserSGLDTBalance(arg0);
            return result;
        }
    }
    async getUserTransactions(arg0: Principal): Promise<Array<TxRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserTransactions(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserTransactions(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserUNIDeposits(arg0: Principal): Promise<Array<UniDepositRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserUNIDeposits(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserUNIDeposits(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeMinterDepositAddress(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeMinterDepositAddress();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeMinterDepositAddress();
            return result;
        }
    }
    async isAdminCaller(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdminCaller();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdminCaller();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async migrated_getAllBridgeRequests(): Promise<Array<BridgeRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.migrated_getAllBridgeRequests();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.migrated_getAllBridgeRequests();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async migrated_getAllSGLDTRequests(): Promise<Array<sGLDTRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.migrated_getAllSGLDTRequests();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.migrated_getAllSGLDTRequests();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async migration_updateBalance(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.migration_updateBalance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.migration_updateBalance(arg0);
            return result;
        }
    }
    async mintBankingBraveTokens(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.mintBankingBraveTokens(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.mintBankingBraveTokens(arg0, arg1);
            return result;
        }
    }
    async refreshTreasuryBalances(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.refreshTreasuryBalances();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.refreshTreasuryBalances();
            return result;
        }
    }
    async rejectBridgeRequest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectBridgeRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectBridgeRequest(arg0);
            return result;
        }
    }
    async rejectSGLDTExchangeRequest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectSGLDTExchangeRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectSGLDTExchangeRequest(arg0);
            return result;
        }
    }
    async resetMiningPhase(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.resetMiningPhase(arg0);
                return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetMiningPhase(arg0);
            return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async retryUNIDepositPayout(arg0: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.retryUNIDepositPayout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.retryUNIDepositPayout(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async selfInitializeMinterAddress(): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.selfInitializeMinterAddress();
                return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.selfInitializeMinterAddress();
            return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async setBatPoolBalance(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setBatPoolBalance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setBatPoolBalance(arg0);
            return result;
        }
    }
    async setLiveExchangeRate(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setLiveExchangeRate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setLiveExchangeRate(arg0);
            return result;
        }
    }
    async setSGLDTTreasuryBalance(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSGLDTTreasuryBalance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSGLDTTreasuryBalance(arg0);
            return result;
        }
    }
    async setUNIExchangeRate(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUNIExchangeRate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUNIExchangeRate(arg0);
            return result;
        }
    }
    async submitBridgeRequest(arg0: string, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitBridgeRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitBridgeRequest(arg0, arg1);
            return result;
        }
    }
    async submitSGLDTExchangeRequest(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitSGLDTExchangeRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitSGLDTExchangeRequest(arg0);
            return result;
        }
    }
    async submitUNIDeposit(arg0: string, arg1: bigint, arg2: string, arg3: bigint | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitUNIDeposit(arg0, arg1, arg2, to_candid_opt_n37(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitUNIDeposit(arg0, arg1, arg2, to_candid_opt_n37(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async syncLiveExchangeRate(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.syncLiveExchangeRate(arg0);
                return from_candid_variant_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.syncLiveExchangeRate(arg0);
            return from_candid_variant_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async triggerSGLDTPayout(arg0: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.triggerSGLDTPayout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.triggerSGLDTPayout(arg0);
            return result;
        }
    }
    async verifyAndPayUNIDeposit(arg0: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyAndPayUNIDeposit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyAndPayUNIDeposit(arg0);
            return result;
        }
    }
    async verifyEthTransaction(arg0: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyEthTransaction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyEthTransaction(arg0);
            return result;
        }
    }
}
function from_candid_BridgeRequest_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BridgeRequest): BridgeRequest {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_BridgeStatus_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BridgeStatus): BridgeStatus {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_ExchangeStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExchangeStatus): ExchangeStatus {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_TxRecord_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TxRecord): TxRecord {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_TxStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TxStatus): TxStatus {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_TxType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TxType): TxType {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UNIDepositStatus_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UNIDepositStatus): UNIDepositStatus {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_UniDepositRequest_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UniDepositRequest): UniDepositRequest {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        id: bigint;
        status: string;
        sgldtPaid: bigint;
        txHash: string;
    }]): {
    id: bigint;
    status: string;
    sgldtPaid: bigint;
    txHash: string;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _TxStatus;
    description: string;
    tokenSymbol: string;
    timestamp: bigint;
    txType: _TxType;
    amount: bigint;
    errorMsg: [] | [string];
    ethTxHash: [] | [string];
    icpBlockIndex: [] | [bigint];
}): {
    id: string;
    status: TxStatus;
    description: string;
    tokenSymbol: string;
    timestamp: bigint;
    txType: TxType;
    amount: bigint;
    errorMsg?: string;
    ethTxHash?: string;
    icpBlockIndex?: bigint;
} {
    return {
        id: value.id,
        status: from_candid_TxStatus_n11(_uploadFile, _downloadFile, value.status),
        description: value.description,
        tokenSymbol: value.tokenSymbol,
        timestamp: value.timestamp,
        txType: from_candid_TxType_n13(_uploadFile, _downloadFile, value.txType),
        amount: value.amount,
        errorMsg: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.errorMsg)),
        ethTxHash: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.ethTxHash)),
        icpBlockIndex: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.icpBlockIndex))
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _BridgeStatus;
    ethAddress: string;
    submitter: Principal;
    batAmount: bigint;
    timestamp: _Time;
}): {
    id: bigint;
    status: BridgeStatus;
    ethAddress: string;
    submitter: Principal;
    batAmount: bigint;
    timestamp: Time;
} {
    return {
        id: value.id,
        status: from_candid_BridgeStatus_n22(_uploadFile, _downloadFile, value.status),
        ethAddress: value.ethAddress,
        submitter: value.submitter,
        batAmount: value.batAmount,
        timestamp: value.timestamp
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ExchangeStatus;
    submitter: Principal;
    bbTokenAmount: bigint;
    sgldAmountCalculated: bigint;
    timestamp: _Time;
}): {
    id: bigint;
    status: ExchangeStatus;
    submitter: Principal;
    bbTokenAmount: bigint;
    sgldAmountCalculated: bigint;
    timestamp: Time;
} {
    return {
        id: value.id,
        status: from_candid_ExchangeStatus_n27(_uploadFile, _downloadFile, value.status),
        submitter: value.submitter,
        bbTokenAmount: value.bbTokenAmount,
        sgldAmountCalculated: value.sgldAmountCalculated,
        timestamp: value.timestamp
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _UNIDepositStatus;
    uniAmount: bigint;
    ethAddress: string;
    submitter: Principal;
    lockedExchangeRate: [] | [bigint];
    sgldtPaid: bigint;
    timestamp: _Time;
    txHash: string;
}): {
    id: bigint;
    status: UNIDepositStatus;
    uniAmount: bigint;
    ethAddress: string;
    submitter: Principal;
    lockedExchangeRate?: bigint;
    sgldtPaid: bigint;
    timestamp: Time;
    txHash: string;
} {
    return {
        id: value.id,
        status: from_candid_UNIDepositStatus_n31(_uploadFile, _downloadFile, value.status),
        uniAmount: value.uniAmount,
        ethAddress: value.ethAddress,
        submitter: value.submitter,
        lockedExchangeRate: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.lockedExchangeRate)),
        sgldtPaid: value.sgldtPaid,
        timestamp: value.timestamp,
        txHash: value.txHash
    };
}
function from_candid_sGLDTRequest_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _sGLDTRequest): sGLDTRequest {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Failed: null;
} | {
    Confirmed: null;
} | {
    Completed: null;
} | {
    Pending: null;
}): TxStatus {
    return "Failed" in value ? TxStatus.Failed : "Confirmed" in value ? TxStatus.Confirmed : "Completed" in value ? TxStatus.Completed : "Pending" in value ? TxStatus.Pending : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Mint: null;
} | {
    Refine: null;
} | {
    Bridge: null;
} | {
    Transfer: null;
}): TxType {
    return "Mint" in value ? TxType.Mint : "Refine" in value ? TxType.Refine : "Bridge" in value ? TxType.Bridge : "Transfer" in value ? TxType.Transfer : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): BridgeStatus {
    return "pending" in value ? BridgeStatus.pending : "approved" in value ? BridgeStatus.approved : "rejected" in value ? BridgeStatus.rejected : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    paid: null;
} | {
    confirmed: null;
} | {
    processing: null;
} | {
    failed: null;
}): UNIDepositStatus {
    return "pending" in value ? UNIDepositStatus.pending : "paid" in value ? UNIDepositStatus.paid : "confirmed" in value ? UNIDepositStatus.confirmed : "processing" in value ? UNIDepositStatus.processing : "failed" in value ? UNIDepositStatus.failed : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BridgeRequest>): Array<BridgeRequest> {
    return value.map((x)=>from_candid_BridgeRequest_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_sGLDTRequest>): Array<sGLDTRequest> {
    return value.map((x)=>from_candid_sGLDTRequest_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UniDepositRequest>): Array<UniDepositRequest> {
    return value.map((x)=>from_candid_UniDepositRequest_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TxRecord>): Array<TxRecord> {
    return value.map((x)=>from_candid_TxRecord_n9(_uploadFile, _downloadFile, x));
}
function to_candid_TxRecord_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TxRecord): _TxRecord {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_TxStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TxStatus): _TxStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_TxType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TxType): _TxType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: TxStatus;
    description: string;
    tokenSymbol: string;
    timestamp: bigint;
    txType: TxType;
    amount: bigint;
    errorMsg?: string;
    ethTxHash?: string;
    icpBlockIndex?: bigint;
}): {
    id: string;
    status: _TxStatus;
    description: string;
    tokenSymbol: string;
    timestamp: bigint;
    txType: _TxType;
    amount: bigint;
    errorMsg: [] | [string];
    ethTxHash: [] | [string];
    icpBlockIndex: [] | [bigint];
} {
    return {
        id: value.id,
        status: to_candid_TxStatus_n3(_uploadFile, _downloadFile, value.status),
        description: value.description,
        tokenSymbol: value.tokenSymbol,
        timestamp: value.timestamp,
        txType: to_candid_TxType_n5(_uploadFile, _downloadFile, value.txType),
        amount: value.amount,
        errorMsg: value.errorMsg ? candid_some(value.errorMsg) : candid_none(),
        ethTxHash: value.ethTxHash ? candid_some(value.ethTxHash) : candid_none(),
        icpBlockIndex: value.icpBlockIndex ? candid_some(value.icpBlockIndex) : candid_none()
    };
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TxStatus): {
    Failed: null;
} | {
    Confirmed: null;
} | {
    Completed: null;
} | {
    Pending: null;
} {
    return value == TxStatus.Failed ? {
        Failed: null
    } : value == TxStatus.Confirmed ? {
        Confirmed: null
    } : value == TxStatus.Completed ? {
        Completed: null
    } : value == TxStatus.Pending ? {
        Pending: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TxType): {
    Mint: null;
} | {
    Refine: null;
} | {
    Bridge: null;
} | {
    Transfer: null;
} {
    return value == TxType.Mint ? {
        Mint: null
    } : value == TxType.Refine ? {
        Refine: null
    } : value == TxType.Bridge ? {
        Bridge: null
    } : value == TxType.Transfer ? {
        Transfer: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
